server.port = 8080

management.endpoints.web.exposure.include=*

logging.level.root=info
logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%-30thread]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
logging.logback.rollingpolicy.max-file-size=1MB
logging.logback.rollingpolicy.max-history=10
logging.file.name=logFile.log

spring.thymeleaf.cache=false

spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
spring.r2dbc.username=sa
spring.r2dbc.password=
#logging.level.io.r2dbc.spi=DEBUG
#logging.level.io.r2dbc.h2=DEBUG
spring.sql.init.schema-locations=classpath:/db/schema.sql
