spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#logging.level.liquibase=DEBUG
#logging.level.org.liquibase=DEBUG
#logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
#
#logging.level.org.springframework.jdbc.datasource=DEBUG
#logging.level.org.springframework.data.r2dbc=DEBUG
#logging.level.io.r2dbc=DEBUG

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/experiments
spring.r2dbc.username=experiments_user
spring.r2dbc.password=experiments_user_password
spring.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/experiments
spring.datasource.username=experiments_user
spring.datasource.password=experiments_user_password
spring.jpa.hibernate.ddl-auto=none
spring.r2dbc.generate-ddl=false
